name: ai_buddy
description: AI Buddy app.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Common
  loggy: ^2.0.3
  go_router: ^11.1.3
  url_launcher: ^6.1.14
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.0
  hive: ^2.2.3
  flutter_chat_ui: ^1.6.12
  uuid: ^4.3.3
  flutter_chat_types: ^3.6.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  dio: ^5.4.0
  path_provider: ^2.1.2
  flutter_secure_storage: ^4.2.1
  flutter_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.4
  file_picker: ^6.1.1
  image_picker: ^1.0.7
  syncfusion_flutter_pdf: ^24.2.4
  syncfusion_flutter_pdfviewer: ^24.2.5
  flutter_spinkit: ^5.2.0
  lottie: ^3.0.0

  # iOS
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  freezed: ^2.4.7
  hive_generator: ^2.0.0
  json_serializable: ^6.7.1
  mockito: ^5.4.4
  msix: ^3.16.7

dependency_overrides:
  web: ^0.3.0  # Force web package version to match Flutter SDK requirement
  google_fonts: 6.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/animations/

msix_config:
  display_name: AI Buddy
  publisher_display_name: SuperAwesomeApps
  identity_name: com.superawesomeapps.ai-buddy
  msix_version: 1.0.0.0
  logo_path: windows/runner/resources/app_icon.ico
  capabilities: internetClient
  languages: en-us
  store: false
  publisher: CN=SuperAwesomeApps, O=SuperAwesomeApps Corporation, C=US
  sign_msix: false  # Set to true if you have a code signing certificate
  certificate_path: null
  certificate_password: null